#include "QTtry1.h"
#include<iostream>
#include<QLabel>
#include<qscreen.h>
#include <QtWidgets/QApplication>
#include<sstream>

int main(int argc, char *argv[])
{
    using namespace std;
    QApplication a(argc, argv);
    QTtry1 w;
    w.setGeometry(0, 0, 1920, 1440);
    //w.setWindowState(Qt::WindowMaximized);
    QLabel lab(&w);
    lab.setGeometry(0, 300, 100, 100);
    std::stringstream ss;
    string str;
    getline(ss, str);
    QString s1;
    s1.append(str);
    lab.setText(s1);

    w.lab = &lab;
    
    w.show();


    
    return a.exec();
}

// 从excel导入
// 创建空白进程
// 新建资源列
// 随机填充空白数据
// 随机生成新进程
// 加入新资源

// 随机生成初始数据
// 执行银行家算法

// 随机生成剩余服务时间

/*

# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
include(QTtry1.pri)
TARGET = QTtry1
DESTDIR = ./x64/Release
QT += webview
CONFIG += release
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
QT+=widgets
INCLUDEPATH+= D:/MyLib/libxl-4.2.0/include_cpp/
LIBS += -LD:/MyLib/libxl-4.2.0/lib -llibxl64
QT += core gui webenginewidgets


*/